/**
 * Vendors the three webfonts into public/fonts/ so the game never asks the
 * network for its own typography.
 *
 * HEXHOLD ships as a desktop binary. A player who launches it on a plane gets
 * whatever `serif` means on their machine unless the fonts are in the build,
 * and the entire display face — Cinzel — is what the title, the hand names and
 * the Market headings are made of. Losing it offline is not a graceful
 * degradation, it is a different game.
 *
 * All three faces are SIL Open Font License 1.1, which permits redistribution.
 * Only the `latin` subset is taken; the copy is English throughout.
 *
 * Run: node scripts/vendor-fonts.mjs   (only needed when a weight changes)
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const OUT = path.resolve('public/fonts');
mkdirSync(OUT, { recursive: true });

// A browser UA is required, or the API serves legacy TTF instead of woff2.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'Cinzel', slug: 'cinzel', weights: [500, 600, 700, 900] },
  { name: 'Inter', slug: 'inter', weights: [400, 500, 600, 700, 800] },
  { name: 'JetBrains Mono', slug: 'jetbrains-mono', weights: [500, 700] },
];

const faces = [];

for (const fam of FAMILIES) {
  const q = `${fam.name.replace(/ /g, '+')}:wght@${fam.weights.join(';')}`;
  const url = `https://fonts.googleapis.com/css2?family=${q}&display=swap`;
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  // Each @font-face block is preceded by a /* subset */ comment. Keep latin.
  const blocks = css.split('@font-face').slice(1);
  for (const block of blocks) {
    const weight = Number(/font-weight:\s*(\d+)/.exec(block)?.[1]);
    const src = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1] ?? '';
    // The latin subset is the one that covers ASCII; latin-ext starts at U+0100.
    const isLatin = range.includes('U+0000') || range.includes('U+0041');
    if (!src || !weight || !isLatin) continue;
    if (!fam.weights.includes(weight)) continue;

    const file = `${fam.slug}-${weight}.woff2`;
    const bytes = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
    writeFileSync(path.join(OUT, file), bytes);
    faces.push({ family: fam.name, weight, file, bytes: bytes.length });
    console.log(`  ${file.padEnd(24)} ${(bytes.length / 1024).toFixed(1)} KB`);
  }
}

const css = `/*
 * Generated by scripts/vendor-fonts.mjs — do not edit by hand.
 *
 * Cinzel, Inter and JetBrains Mono, SIL Open Font License 1.1, latin subset.
 * Served from the build so the game never needs the network to look like
 * itself.
 */
${faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: block;
  src: url('./${f.file}') format('woff2');
}`,
  )
  .join('\n')}
`;

writeFileSync(path.join(OUT, 'fonts.css'), css);
const total = faces.reduce((n, f) => n + f.bytes, 0);
console.log(`\n  ${faces.length} faces, ${(total / 1024).toFixed(0)} KB total → public/fonts/`);
